### ISSUE TITLE
bibdata refactor changes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton-iec#7]
The changes in https://github.com/metanorma/isobib/issues/42 are to be replicated in this gem. The only grammar difference is the presence of subparts in the structuredidentifier (as an attribute) and document identifier (as a text component).

**Comment by andrew2net** [comment]
@opoudjis where I can find `iec` grammar?

**Comment by opoudjis** [comment]
IEC is identical grammatically to ISO. The only difference at all is that IEC documents can have subparts as well as parts, which is reflected in the structured identifier; but the two now share the same grammar anyway, including subparts.
